#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Load Libs ---------------------------------------------------------------
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
library(tidyverse)
library(here)

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Load Data ---------------------------------------------------------------
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
data <- read_rds(here("Data/NSCG_Master.rds"))

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Make Labels -------------------------------------------------------------
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Major_labels <- data %>% 
  select(Major) %>% 
  distinct(Major) %>% 
  arrange(Major) 

Major_labels <- Major_labels %>% 
  mutate(Major_Label = case_when(Major == 116710L ~ "Computer and information sciences",
                                 Major == 116730L ~ "Computer science",
                                 Major == 116740L ~ "Computer systems analysis",
                                 Major == 116760L ~ "Information services and systems",
                                 Major == 116770L ~ "OTHER computer and information sciences",
                                 Major == 128410L ~ "Applied mathematics",
                                 Major == 128420L ~ "Mathematics, general",
                                 Major == 128430L ~ "Operations research",
                                 Major == 128440L ~ "Statistics",
                                 Major == 128450L ~ "OTHER mathematics",
                                 Major == 216050L ~ "Animal sciences",
                                 Major == 216060L ~ "Food sciences and technology",
                                 Major == 216070L ~ "Plant sciences",
                                 Major == 216080L ~ "OTHER agricultural sciences",
                                 Major == 226310L ~ "Biochemistry and biophysics",
                                 Major == 226320L ~ "Biology, general",
                                 Major == 226330L ~ "Botany",
                                 Major == 226340L ~ "Cell and molecular biology",
                                 Major == 226350L ~ "Ecology",
                                 Major == 226360L ~ "Genetics, animal and plant",
                                 Major == 226370L ~ "Microbiological sciences and immunology",
                                 Major == 226380L ~ "Nutritional sciences",
                                 Major == 226390L ~ "Pharmacology, human and animal",
                                 Major == 226400L ~ "Physiology and pathology, human and animal",
                                 Major == 226410L ~ "Zoology, general",
                                 Major == 226420L ~ "OTHER biological sciences",
                                 Major == 236800L ~ "Environmental science or studies",
                                 Major == 236810L ~ "Forestry sciences",
                                 Major == 318730L ~ "Chemistry, except biochemistry",
                                 Major == 328720L ~ "Atmospheric sciences and meteorology",
                                 Major == 328740L ~ "Earth sciences",
                                 Major == 328750L ~ "Geology",
                                 Major == 328760L ~ "Geological sciences, other",
                                 Major == 328770L ~ "Oceanography",
                                 Major == 338710L ~ "Astronomy and astrophysics",
                                 Major == 338780L ~ "Physics",
                                 Major == 348790L ~ "OTHER physical sciences",
                                 Major == 349910L ~ "Science, unclassified",
                                 Major == 416010L ~ "Agricultural economics",
                                 Major == 419230L ~ "Economics",
                                 Major == 429020L ~ "Public policy studies",
                                 Major == 429270L ~ "International relations",
                                 Major == 429280L ~ "Political science and government",
                                 Major == 437040L ~ "Educational psychology",
                                 Major == 438910L ~ "Clinical psychology",
                                 Major == 438920L ~ "Counseling psychology",
                                 Major == 438930L ~ "Experimental psychology",
                                 Major == 438940L ~ "General psychology",
                                 Major == 438950L ~ "Industrial/Organizational psychology",
                                 Major == 438960L ~ "Social psychology",
                                 Major == 438970L ~ "OTHER psychology",
                                 Major == 449210L ~ "Anthropology and archaeology",
                                 Major == 449220L ~ "Criminology",
                                 Major == 449290L ~ "Sociology",
                                 Major == 456200L ~ "Area and Ethnic Studies",
                                 Major == 457710L ~ "Linguistics",
                                 Major == 458610L ~ "Philosophy of science",
                                 Major == 459240L ~ "Geography",
                                 Major == 459250L ~ "History of science",
                                 Major == 459300L ~ "OTHER social sciences",
                                 Major == 517210L ~ "Aerospace, aeronautical and astronautical engineering",
                                 Major == 527250L ~ "Chemical engineering",
                                 Major == 537230L ~ "Architectural engineering",
                                 Major == 537260L ~ "Civil engineering",
                                 Major == 547270L ~ "Computer and systems engineering",
                                 Major == 547280L ~ "Electrical, electronics and communications engineering",
                                 Major == 557330L ~ "Industrial and manufacturing engineering",
                                 Major == 567350L ~ "Mechanical engineering",
                                 Major == 577220L ~ "Agricultural engineering",
                                 Major == 577240L ~ "Bioengineering and biomedical engineering",
                                 Major == 577290L ~ "Engineering sciences, mechanics and physics",
                                 Major == 577300L ~ "Environmental engineering",
                                 Major == 577310L ~ "Engineering, general",
                                 Major == 577320L ~ "Geophysical and geological engineering",
                                 Major == 577340L ~ "Materials engineering, including ceramics and textiles",
                                 Major == 577360L ~ "Metallurgical engineering",
                                 Major == 577370L ~ "Mining and minerals engineering",
                                 Major == 577380L ~ "Naval architecture and marine engineering",
                                 Major == 577390L ~ "Nuclear engineering",
                                 Major == 577400L ~ "Petroleum engineering",
                                 Major == 577410L ~ "OTHER engineering",
                                 Major == 617810L ~ "Audiology and speech pathology",
                                 Major == 617820L ~ "Health services administration",
                                 Major == 617830L ~ "Health/medical assistants",
                                 Major == 617840L ~ "Health/medical technologies",
                                 Major == 617850L ~ "Medical preparatory programs (e.g. pre-dentistry,-medical,veterinary)",
                                 Major == 617860L ~ "Medicine (dentistry,optometry,osteopathic,podiatry,veterinary)",
                                 Major == 617870L ~ "Nursing (4 years or longer program)",
                                 Major == 617880L ~ "Pharmacy",
                                 Major == 617890L ~ "Physical therapy and other rehabilitation/therapeutic services",
                                 Major == 617900L ~ "Public health (including environmental health and epidemiology)",
                                 Major == 617910L ~ "OTHER health/medical sciences",
                                 Major == 627020L ~ "Computer teacher education",
                                 Major == 627060L ~ "Mathematics teacher education",
                                 Major == 627090L ~ "Science teacher education",
                                 Major == 627120L ~ "Social science teacher education",
                                 Major == 636720L ~ "Computer programming",
                                 Major == 636750L ~ "Data processing",
                                 Major == 637510L ~ "Electrical and electronic technologies",
                                 Major == 637520L ~ "Industrial production technologies",
                                 Major == 637530L ~ "Mechanical engineering-related technologies",
                                 Major == 637540L ~ "OTHER engineering-related technologies",
                                 Major == 646100L ~ "Architecture/Environmental Design",
                                 Major == 646520L ~ "Actuarial science",
                                 Major == 716020L ~ "OTHER agricultural business and production",
                                 Major == 716510L ~ "Accounting",
                                 Major == 716530L ~ "Business administration and management",
                                 Major == 716540L ~ "Business, general",
                                 Major == 716550L ~ "Business and managerial economics",
                                 Major == 716570L ~ "Financial management",
                                 Major == 716590L ~ "OTHER business management/administrative services",
                                 Major == 727010L ~ "Education administration",
                                 Major == 727030L ~ "Counselor education and guidance services",
                                 Major == 727050L ~ "Elementary teacher education",
                                 Major == 727070L ~ "Physical education and coaching",
                                 Major == 727080L ~ "Pre-school/kindergarten/early childhood teacher education",
                                 Major == 727100L ~ "Secondary teacher education",
                                 Major == 727110L ~ "Special education",
                                 Major == 727130L ~ "OTHER education",
                                 Major == 738620L ~ "OTHER philosophy, religion, theology",
                                 Major == 739100L ~ "Social Work",
                                 Major == 746560L ~ "Business marketing/marketing management",
                                 Major == 746580L ~ "Marketing research",
                                 Major == 757600L ~ "English Language, literature and letters",
                                 Major == 757720L ~ "OTHER foreign languages and literature",
                                 Major == 758200L ~ "Liberal Arts/General Studies",
                                 Major == 759260L ~ "History, other",
                                 Major == 759410L ~ "Dramatic arts",
                                 Major == 759420L ~ "Fine arts, all fields",
                                 Major == 759430L ~ "Music, all fields",
                                 Major == 759440L ~ "OTHER visual and performing arts",
                                 Major == 766610L ~ "Communications, general",
                                 Major == 766620L ~ "Journalism",
                                 Major == 766630L ~ "OTHER communications",
                                 Major == 766820L ~ "OTHER natural resources and conservation",
                                 Major == 766900L ~ "Criminal Justice/Protective Services",
                                 Major == 767600L ~ "An Unknown Field",
                                 Major == 768000L ~ "Home Economics",
                                 Major == 768100L ~ "Law/Prelaw/Legal Studies",
                                 Major == 768300L ~ "Library Science",
                                 Major == 768500L ~ "Parks, Recreation, Leisure, and Fitness Studies",
                                 Major == 769010L ~ "Public administration",
                                 Major == 769030L ~ "OTHER public affairs",
                                 Major == 769950L ~ "OTHER FIELDS (Not Listed)"))

write_csv(Major_labels, here("Data/Major-Labels.csv"))
